artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/5e014f7cffcb417291b54e0e7f7dcf17/artifacts
end_time: 1751936943410
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 5e014f7cffcb417291b54e0e7f7dcf17
run_name: Default
run_uuid: 5e014f7cffcb417291b54e0e7f7dcf17
source_name: ''
source_type: 4
source_version: ''
start_time: 1751936943399
status: 3
tags: []
user_id: mle-user
