artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/a2d6b37de78c4a7bbf6872db6d7ea5cd/artifacts
end_time: 1751936830794
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: a2d6b37de78c4a7bbf6872db6d7ea5cd
run_name: Default
run_uuid: a2d6b37de78c4a7bbf6872db6d7ea5cd
source_name: ''
source_type: 4
source_version: ''
start_time: 1751936830779
status: 3
tags: []
user_id: mle-user
